server:
  port: 8082

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      # Configuración de SERVIDOR (Necesaria para validar entrada)
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/ecommerce-realm"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

order:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh"
