server:
  port: 8082

spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      # Configuración de SERVIDOR (Necesaria para validar entrada)
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/ecommerce-realm"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

order:
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,refresh,circuitbreakers"
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        SlidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      inventory:
        maxRetryAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
# # Se deshabilita porque se solventa usando una Arquitectura Orientada a Eventos - RabbitMQ
#  timelimiter:
#    instances:
#      inventory:
#        timeoutDuration: 3s
#        cancelRunningFuture: true
